name: Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Node js configuration
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm install
        
    - name: Run tests
      run: npm test

    - name: Check code style
      run: |
        npm install eslint --save-dev
        npx eslint .
